apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: pr-pe-code-review              # Matches ${repo.replace('/', '-')}
  namespace: default                    # Matches the namespace in the URL
  annotations:
    github.com/project-slug: m-sruthika-10/pr-pe-code-review  # Added correct annotation
    backstage.io/github-repo: m-sruthika-10/pr-pe-code-review # Optional, can be kept for compatibility
    jira_key: DE
    sonar_key: project-mdm-qaspec-ui
    syscoscore.io/enabled: "true"
spec:
  type: service
  lifecycle: experimental
  owner: m-sruthika-10      # Use 'user:namespace/username' format for owner
